### ISSUE TITLE
Firefox Webextension

### ISSUE THREAD

**Issue by brian-girko** [jeromewu/tesseract.js-chrome-extension#2] opened 2019-06-17 07:09 UTC
I am not able to run this extension in FF. Any plan to make it compatible?

**Comment by jeromewu** [comment] 2019-07-02 16:08
Well, Firefox and Chrome are using very different mechanism in writing extension, it it not possible to directly using one extension in another one. It takes time to do a rewrite, and as I have no experience in writing Firefox extension, it will take some time to survey.

**Comment by WebReflection** [comment] 2019-12-17 10:40
I think all you have to do is:

```js
const browser = window.browser || chrome;

browser.extension.getURL(...)
```

as the `getURL` seems to be the only thing using the extension API, and that's consistent with both browsers.

**Comment by WebReflection** [comment] 2019-12-17 10:41
Actually, that'd be:

```js
const extension = window.browser ? browser.extension : chrome.runtime;

extension.getURL(...)
```

**Comment by WebReflection** [comment] 2019-12-18 14:49
P.S. now that my 2 PRs landed, I can confirm this extension works pretty damn well in Firefox too so I think this can be closed.

**Closed** 2019-12-18 15:13 UTC
